import React from "react";
import SourceLine, { VerificationBadge } from "./SourceLine";
import { STATUS_LABEL, evaluateTransport } from "../engine/transport.js";

// Step 2 — the verdict. The STATUS is the headline; the score is secondary.
const STATUS_COPY = {
  READY: { word: "READY", line: "Your trip works for your pet." },
  ACTION_NEEDED: { word: "ACTION NEEDED", line: "One thing is blocking this trip. We found a way round it." },
  BLOCKED: { word: "BLOCKED", line: "We could not find a compatible option in the current dataset." },
  INFORMATION_REQUIRED: { word: "MORE INFO NEEDED", line: "Add a little more detail and we can finish the check." },
  NOT_VERIFIED: { word: "NOT VERIFIED", line: "We have no checked source for this stay, so we will not call it safe." }
};

export default function TripStatus({ pet, trip, readiness, transport, onSwitchStay, onViewItinerary, children }) {
  const copy = STATUS_COPY[readiness.status] ?? STATUS_COPY.NOT_VERIFIED;
  const transportResult = transport ? evaluateTransport(pet, transport) : null;
  const tone = readiness.status === "READY" ? "ok" : readiness.status === "ACTION_NEEDED" ? "warn" : readiness.status === "BLOCKED" ? "block" : "info";

  return (
    <section>
      <div className={`status-card ${tone}`}>
        <div>
          <div className="mini-label">YOUR TRIP STATUS</div>
          <p className="status-word">{copy.word}</p>
          <p className="status-line">{copy.line}</p>
        </div>
        <div className="status-score">
          <span>{readiness.score}<small>/100</small></span>
          <small>Readiness score, derived from structured constraints — not generated by a model.</small>
        </div>
      </div>

      {transport && transportResult && (
        <div className="source-strip">
          <div>
            <b>Selected transport:</b> {transport.name} — {STATUS_LABEL[transportResult.status]}
            <br />{transportResult.summary}
          </div>
          <VerificationBadge status={transport.provenance.verificationStatus} />
        </div>
      )}

      {readiness.blocker && (
        <article className="alert">
          <div className="alert-icon" aria-hidden="true">!</div>
          <div>
            <span className="section-kicker">STAY CONFLICT</span>
            <h2>{readiness.blocker.place.name} isn't compatible</h2>
            <p>{readiness.blocker.reason}</p>
            <SourceLine record={readiness.blocker.place} />
          </div>
        </article>
      )}

      {readiness.blocker && readiness.alternative ? (
        <article id="compatible-stay" className="card">
          <div className="section-heading">
            <div>
              <span className="section-kicker">RECOMMENDED ALTERNATIVE</span>
              <h2>{readiness.alternative.place.name}</h2>
              <p>{readiness.alternative.reason}</p>
              <SourceLine record={readiness.alternative.place} />
            </div>
            <span className="status compatible">COMPATIBLE</span>
          </div>
          {readiness.alternatives.length > 1 && (
            <p className="trust-label">{readiness.alternatives.length} compatible stays found in this dataset.</p>
          )}
          <div className="actions">
            <button onClick={() => onSwitchStay(readiness.alternative.place.id)}>Switch to this stay →</button>
          </div>
        </article>
      ) : readiness.blocker ? (
        <article className="card">
          <h2>No compatible stay found in the current dataset.</h2>
          <p>Try another destination, or adjust your pet's details. We will not suggest a stay we cannot check.</p>
        </article>
      ) : (
        <article className="card course-corrected">
          <span className="section-kicker">✓ COURSE CORRECTED</span>
          <h2>Your selected stay now fits {pet.name || "your pet"}</h2>
          <p>{readiness.selectedAccommodation.name} has updated the trip plan for {trip?.to || "your destination"}.</p>
          <SourceLine record={readiness.selectedAccommodation} />
          <div className="actions">
            <button onClick={onViewItinerary}>View updated itinerary →</button>
          </div>
        </article>
      )}

      {children}
    </section>
  );
}
